### ISSUE TITLE
您好，请问单卡训练RGB-T数据集时，加载738张图片就会报错，这是什么原因呢，该怎么解决它？

### ISSUE THREAD

**Issue by shensongli** [huaaaliu/RGBX_Semantic_Segmentation#28]
报错如下：
 warnings.warn(
07 15:24:26 PyTorch Version 1.11.0
07 15:24:26 using devices 0
07 15:24:26 Using backbone: Segformer-B2
07 15:24:27 Using MLP Decoder
07 15:24:27 Loading pretrained model: /workspace/cmx_5781/RGBX/pretrained/segformer/mit_b2.pth
07 15:24:28 Load model, Time usage:
        IO: 0.6079375743865967, initialize parameters: 0.0488431453704834
07 15:24:28 Initing weights ...
07 15:24:31 begin trainning:
Epoch 1/500 Iter 738/962: lr=4.5967e-06 loss=1.2658 total_loss=0.9264: [04:21<01:19, 2.83it/s]libpng error: Read Error
Epoch 1/500 Iter 738/962: lr=4.5967e-06 loss=1.2658 total_loss=0.9264: [04:21<01:19, 2.82it/s]
07 15:28:52 WRN A exception occurred during Engine initialization, give up running process
Traceback (most recent call last):
  File "train.py", line 112, in <module>
    minibatch = dataloader.next()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/cmx_5781/RGBX/dataloader/RGBXDataset.py", line 54, in __getitem__
    x = cv2.merge([x, x, x])
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'merge'
> Overload resolution failed:
>  - Can't parse 'mv'. Sequence item with index 0 has a wrong type
>  - Can't parse 'mv'. Sequence item with index 0 has a wrong type

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 553) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-07_15:28:56
  host      : f045835eb25d
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 553)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

配置文件如下：
> # Dataset config
"""Dataset Path"""
C.dataset_name = 'RGBT'
C.dataset_path = osp.join(C.root_dir, 'datasets', 'RGBT')
C.rgb_root_folder = osp.join(C.dataset_path, 'RGB')
C.rgb_format = '.png'
C.gt_root_folder = osp.join(C.dataset_path, 'GT')
C.gt_format = '.png'
C.gt_transform = False
C.x_root_folder = osp.join(C.dataset_path, 'T')
C.x_format = '.png'
C.x_is_single_channel = True 
C.train_source = osp.join(C.dataset_path, "train.txt")
C.eval_source = osp.join(C.dataset_path, "test.txt")
C.is_test = False
C.num_train_imgs = 1922
C.num_eval_imgs = 966
C.num_classes = 6
C.class_names =  [‘Unlabeled'，Insulator','Current Transformer','Voltage Transformer','Lightning Arrester','Bushing']

RGBXDatasets.py修改了这一部分：
    def __getitem__(self, index):
        if self._file_length is not None:
            item_name = self._construct_new_file_names(self._file_length)[index]
        else:
            item_name = self._file_names[index]
        x_name = "T" + item_name[3:]
        gt_name = "GT" + item_name[3:]
        rgb_path = os.path.join(self._rgb_path, item_name + self._rgb_format)
        x_path = os.path.join(self._x_path, x_name + self._x_format)
        gt_path = os.path.join(self._gt_path, gt_name + self._gt_format)

**Comment by jamycheung** [comment]
Hi, thanks for your interest. It seems like an error from dataloarder. Did you check the original data whether it is corrupted?
